textshown = ""
textinhand = ""
refresh = false
basex = room_width / 2
baseytrue = room_height + 15
finalytrue = room_height - 50
offsety = 0
finaly = finalytrue - offsety
basey = baseytrue + offsety
currenty = basey
textstage = 0
duration = 200
wiggleness = 1